[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "plankapy>=2.2.2",
    "python-dotenv>=1.1.1",
    "requests==2.32.3",
]
